name = "taplo"
type = "cli"

[resolve]
git-url = "https://github.com/tamasfe/taplo"
version-pattern = "^((?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+))$"

[platform.linux]
download-file = "taplo-linux-{arch}.gz"
exe-path = "taplo-linux-{arch}"

[platform.macos]
download-file = "taplo-darwin-{arch}.gz"
exe-path = "taplo-darwin-{arch}"

[platform.windows]
download-file = "taplo-windows-{arch}.zip"
exe-path = "taplo.exe"

[install]
download-url = "https://github.com/tamasfe/taplo/releases/download/{version}/{download_file}"
