name = "cloud-provider-kind"
type = "cli"

[resolve]
git-url = "https://github.com/kubernetes-sigs/cloud-provider-kind"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[platform.linux]
download-file = "cloud-provider-kind_{version}_linux_{arch}.tar.gz"
checksum-file = "cloud-provider-kind_{version}_checksums.txt"
exe-path = "cloud-provider-kind"

[platform.macos]
download-file = "cloud-provider-kind_{version}_darwin_{arch}.tar.gz"
checksum-file = "cloud-provider-kind_{version}_checksums.txt"
exe-path = "cloud-provider-kind"

[platform.windows]
download-file = "cloud-provider-kind_{version}_windows_{arch}.tar.gz"
checksum-file = "cloud-provider-kind_{version}_checksums.txt"
exe-path = "cloud-provider-kind.exe"

[install]
download-url = "https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/kubernetes-sigs/cloud-provider-kind/releases/download/v{version}/{checksum_file}"
